from datetime import datetime
from rich.panel import Panel
from rich.console import Console

console = Console()

def generate_report(cfg):
    """
    Fungsi untuk generate incident report (dummy)
    Args:
        cfg (dict): dictionary berisi base_url dan api_token (untuk API nanti)
    """
    # Dummy alert data
    alert = {
        "id": "ALERT-123",
        "severity": "High",
        "status": "Open",
        "description": "Malware detected running suspicious process",
        "endpoint": {
            "name": "SERVER-01",
            "os": "Windows Server 2019",
            "last_seen": "2025-08-19 10:30:00",
            "ip": ["192.168.100.50", "192.168.134.146"],
            "agent_id": "AGENT-987654"
        },
        "process": {
            "name": "malware.exe",
            "path": "C:\\Windows\\Temp\\malware.exe",
            "hash": "abcd1234efgh5678ijkl9012mnop3456",
            "source": "SentinelOne EDR"
        },
        "network": {
            "connections": ["8.8.8.8:443", "45.33.32.156:80"],
            "domains": ["malicious.com", "c2server.net"]
        },
        "recommendations": [
            "Isolate the endpoint from the network",
            "Run full antivirus and EDR scan",
            "Patch operating system and apps",
            "Reset credentials if suspicious login detected"
        ]
    }

    # Format tanggal report
    date_report = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    # Buat isi report
    report_content = f"""
===============================
        INCIDENT REPORT
===============================
Report Date : {date_report}
Report ID   : {alert['id']}
Status      : {alert['status']}
Severity    : {alert['severity']}
Description : {alert['description']}

--- Endpoint Information ---
Endpoint    : {alert['endpoint']['name']}
OS          : {alert['endpoint']['os']}
Last Seen   : {alert['endpoint']['last_seen']}
IP Address  : {", ".join(alert['endpoint']['ip'])}
Agent ID    : {alert['endpoint']['agent_id']}

--- Threat / Process Detail ---
Process     : {alert['process']['name']}
Path        : {alert['process']['path']}
Hash        : {alert['process']['hash']}
Source      : {alert['process']['source']}

--- Network Indicators ---
Connections : {", ".join(alert['network']['connections'])}
Domains     : {", ".join(alert['network']['domains'])}

--- Recommendations ---
- {alert['recommendations'][0]}
- {alert['recommendations'][1]}
- {alert['recommendations'][2]}
- {alert['recommendations'][3]}

===============================
 Report generated by CLI Tools
 Development by Salman Mustapa
 Created on 19 Agustus 2025
===============================
"""

    # Tampilkan report di terminal
    console.print(Panel(report_content, title="Incident Report", style="bold white"))

    # Simpan ke file txt
    filename = f"report_{alert['id']}.txt"
    with open(filename, "w") as f:
        f.write(report_content)

    console.print(f"[green]Report berhasil disimpan ke {filename}[/green]")